[env:arduino_opta]
platform  = ststm32
board     = opta
framework = arduino

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    arduino-libraries/ArduinoMqttClient @ ^0.1.8

monitor_speed = 115200

build_flags =
    -DARDUINO_OPTA
